name: 'Build & Lint'
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build-lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: yarn && yarn lint && yarn build
